# The documentation for the contents of this file can be found at:
# https://docs.gitlab.com/ce/ci/yaml/README.html

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:1.57.0"

build-test:cargo:
  script:
  - rustc --version && cargo --version
  - cargo build --verbose
  - cargo build --verbose --release
  - cargo test --verbose

lint:clippy:
  script:
  - rustup component add clippy
  - cargo clippy --all-targets --all-features -- -D warnings
